preload = ~/Downloads/wallpapers/arch-linux-1920x1080.jpg
#if more than one preload is desired then continue to preload other backgrounds
preload = ~/Downloads/wallpapers/1056982-widescreen-arch-linux-wallpaper-1920x1080-for-iphone-7.jpg
# .. more preloads

#set the default wallpaper(s) seen on inital workspace(s) --depending on the number of monitors used
wallpaper = HDMI-A-1,~/Downloads/wallpapers/arch-linux-1920x1080.jpg
#if more than one monitor in use, can load a 2nd image
#wallpaper = monitor2,/path/to/next_image.png
# .. more monitors
